name: pfe_can2025
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - transformers
    - datasets
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - plotly
    - tweepy
    - streamlit
    - plotly
    - nltk
    - spacy
